Exercise: Create a dataset for student name, age, marks, department, exam-date

1.Filtering
Display the details of students who scored more than 80 marks

2.Sorting
Sort the DataFrame based on the marks in deciding order.

3.Adding columns
Create a new column called Grade using the following criteria.

Marks>=90-->A
Marks between 80 and 89-->B
Marks between 70 and 79-->C
Marks < 70-->D

4.Modifying columns

Convert all students names into uppercase letter.

5.Removing columns
Remove the Department column from the Dataframe

6.Removing Rows
Remove the student record present at index 3.

7. GroupBy
Find the average marks of students in each department.

8.Aggregate functions
Calculate the following statistics for the Marks column:

Mean
Maximum
Minimum
Sum
Median
Standard Deviation

9.Combining Dataframes
Create another Dataframe containing the following records:
Name  Age Marks Department

Teja  20  87     CSE
Divya 21  91     ECE

Combine it with the original Dataframe.

10. Working with Dates.

Convert the Exam_Date column into datetime format and extract the following:
Day
Month
Year

11.Indexing

Set the Name column as the index and display the details of student "Rahul".

12.Pivot Table
Create a pivot table showing the average Marks for the each Department.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving student_dataset.csv to student_dataset.csv

In [ ]:
import pandas as pd
df= pd.read_csv("student_dataset.csv")

In [ ]:
print(df.head(5))

   student_name  age  marks department   exam_date
0  Aarav Sharma   20     85        CSE  10-05-2026
1    Diya Reddy   21     92        ECE  10-05-2026
2   Rohan Kumar   19     78       MECH  11-05-2026
3   Sneha Patel   20     88        CSE  11-05-2026
4  Vikram Singh   22     74        EEE  12-05-2026

In [ ]:
print(df.tail(5))

    student_name  age  marks department   exam_date
15  Kavya Mishra   20     86         IT  17-05-2026
16   Manoj Yadav   21     69       MECH  18-05-2026
17    Ishita Sen   19     93        CSE  18-05-2026
18   Harsha Teja   20     79        EEE  19-05-2026
19  Neha Chandra   21     90      CIVIL  19-05-2026

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_name  20 non-null     object
 1   age           20 non-null     int64
 2   marks         20 non-null     int64
 3   department    20 non-null     object
 4   exam_date     20 non-null     object
dtypes: int64(2), object(3)
memory usage: 932.0+ bytes
None

1.Filtering :

Display the details of students who scored more than 80 marks

In [ ]:
df[df['marks']>80]

     student_name  age  marks department   exam_date
0    Aarav Sharma   20     85        CSE  10-05-2026
1      Diya Reddy   21     92        ECE  10-05-2026
3     Sneha Patel   20     88        CSE  11-05-2026
5    Ananya Gupta   21     95         IT  12-05-2026
6       Kiran Rao   20     81      CIVIL  13-05-2026
7      Meera Nair   19     89        CSE  13-05-2026
9       Priya Das   20     91        ECE  14-05-2026
11     Nisha Iyer   19     84        EEE  15-05-2026
13    Pooja Menon   21     97        CSE  16-05-2026
14  Siddharth Roy   22     82        ECE  17-05-2026
15   Kavya Mishra   20     86         IT  17-05-2026
17     Ishita Sen   19     93        CSE  18-05-2026
19   Neha Chandra   21     90      CIVIL  19-05-2026

2.Sorting :

Sort the DataFrame based on the marks in descening order.

In [ ]:
df.sort_values(by="marks", ascending=False)

       student_name  age  marks department   exam_date
13      Pooja Menon   21     97        CSE  16-05-2026
5      Ananya Gupta   21     95         IT  12-05-2026
17       Ishita Sen   19     93        CSE  18-05-2026
1        Diya Reddy   21     92        ECE  10-05-2026
9         Priya Das   20     91        ECE  14-05-2026
19     Neha Chandra   21     90      CIVIL  19-05-2026
7        Meera Nair   19     89        CSE  13-05-2026
3       Sneha Patel   20     88        CSE  11-05-2026
15     Kavya Mishra   20     86         IT  17-05-2026
0      Aarav Sharma   20     85        CSE  10-05-2026
11       Nisha Iyer   19     84        EEE  15-05-2026
14    Siddharth Roy   22     82        ECE  17-05-2026
6         Kiran Rao   20     81      CIVIL  13-05-2026
18      Harsha Teja   20     79        EEE  19-05-2026
2       Rohan Kumar   19     78       MECH  11-05-2026
10       Rahul Jain   21     76         IT  15-05-2026
4      Vikram Singh   22     74        EEE  12-05-2026
12  Aditya Kulkarni   20     73      CIVIL  16-05-2026
16      Manoj Yadav   21     69       MECH  18-05-2026
8       Arjun Verma   22     67       MECH  14-05-2026

3.Adding columns:

Create a new column called Grade using the following criteria.

In [ ]:
def assign_grade(mark):
    if mark >= 90:
        return "A"
    elif mark >= 80:
        return "B"
    elif mark >= 70:
        return "C"
    else:
        return "D"

df["Grade"] = df["marks"].apply(assign_grade)

print("DataFrame with Grade Column:")
print(df)

DataFrame with Grade Column:
       student_name  age  marks department   exam_date Grade             Name
0      AARAV SHARMA   20     85        CSE  10-05-2026     B     AARAV SHARMA
1        DIYA REDDY   21     92        ECE  10-05-2026     A       DIYA REDDY
2       ROHAN KUMAR   19     78       MECH  11-05-2026     C      ROHAN KUMAR
3       SNEHA PATEL   20     88        CSE  11-05-2026     B      SNEHA PATEL
4      VIKRAM SINGH   22     74        EEE  12-05-2026     C     VIKRAM SINGH
5      ANANYA GUPTA   21     95         IT  12-05-2026     A     ANANYA GUPTA
6         KIRAN RAO   20     81      CIVIL  13-05-2026     B        KIRAN RAO
7        MEERA NAIR   19     89        CSE  13-05-2026     B       MEERA NAIR
8       ARJUN VERMA   22     67       MECH  14-05-2026     D      ARJUN VERMA
9         PRIYA DAS   20     91        ECE  14-05-2026     A        PRIYA DAS
10       RAHUL JAIN   21     76         IT  15-05-2026     C       RAHUL JAIN
11       NISHA IYER   19     84        EEE  15-05-2026     B       NISHA IYER
12  ADITYA KULKARNI   20     73      CIVIL  16-05-2026     C  ADITYA KULKARNI
13      POOJA MENON   21     97        CSE  16-05-2026     A      POOJA MENON
14    SIDDHARTH ROY   22     82        ECE  17-05-2026     B    SIDDHARTH ROY
15     KAVYA MISHRA   20     86         IT  17-05-2026     B     KAVYA MISHRA
16      MANOJ YADAV   21     69       MECH  18-05-2026     D      MANOJ YADAV
17       ISHITA SEN   19     93        CSE  18-05-2026     A       ISHITA SEN
18      HARSHA TEJA   20     79        EEE  19-05-2026     C      HARSHA TEJA
19     NEHA CHANDRA   21     90      CIVIL  19-05-2026     A     NEHA CHANDRA

In [ ]:
#4. Modifying Columns
#Convert names to uppercase
df["student_name"] = df["student_name"].str.upper()

print("Names converted to uppercase:")
print(df)

Names converted to uppercase:
       student_name  age  marks department   exam_date Grade             Name
0      AARAV SHARMA   20     85        CSE  10-05-2026     B     AARAV SHARMA
1        DIYA REDDY   21     92        ECE  10-05-2026     A       DIYA REDDY
2       ROHAN KUMAR   19     78       MECH  11-05-2026     C      ROHAN KUMAR
3       SNEHA PATEL   20     88        CSE  11-05-2026     B      SNEHA PATEL
4      VIKRAM SINGH   22     74        EEE  12-05-2026     C     VIKRAM SINGH
5      ANANYA GUPTA   21     95         IT  12-05-2026     A     ANANYA GUPTA
6         KIRAN RAO   20     81      CIVIL  13-05-2026     B        KIRAN RAO
7        MEERA NAIR   19     89        CSE  13-05-2026     B       MEERA NAIR
8       ARJUN VERMA   22     67       MECH  14-05-2026     D      ARJUN VERMA
9         PRIYA DAS   20     91        ECE  14-05-2026     A        PRIYA DAS
10       RAHUL JAIN   21     76         IT  15-05-2026     C       RAHUL JAIN
11       NISHA IYER   19     84        EEE  15-05-2026     B       NISHA IYER
12  ADITYA KULKARNI   20     73      CIVIL  16-05-2026     C  ADITYA KULKARNI
13      POOJA MENON   21     97        CSE  16-05-2026     A      POOJA MENON
14    SIDDHARTH ROY   22     82        ECE  17-05-2026     B    SIDDHARTH ROY
15     KAVYA MISHRA   20     86         IT  17-05-2026     B     KAVYA MISHRA
16      MANOJ YADAV   21     69       MECH  18-05-2026     D      MANOJ YADAV
17       ISHITA SEN   19     93        CSE  18-05-2026     A       ISHITA SEN
18      HARSHA TEJA   20     79        EEE  19-05-2026     C      HARSHA TEJA
19     NEHA CHANDRA   21     90      CIVIL  19-05-2026     A     NEHA CHANDRA

In [ ]:
# 5. Removing Columns
# Remove Department column
df_without_dept = df.drop("department", axis=1)

print("DataFrame after removing Department:")
print(df_without_dept)

DataFrame after removing Department:
       student_name  age  marks   exam_date Grade             Name
0      AARAV SHARMA   20     85  10-05-2026     B     AARAV SHARMA
1        DIYA REDDY   21     92  10-05-2026     A       DIYA REDDY
2       ROHAN KUMAR   19     78  11-05-2026     C      ROHAN KUMAR
3       SNEHA PATEL   20     88  11-05-2026     B      SNEHA PATEL
4      VIKRAM SINGH   22     74  12-05-2026     C     VIKRAM SINGH
5      ANANYA GUPTA   21     95  12-05-2026     A     ANANYA GUPTA
6         KIRAN RAO   20     81  13-05-2026     B        KIRAN RAO
7        MEERA NAIR   19     89  13-05-2026     B       MEERA NAIR
8       ARJUN VERMA   22     67  14-05-2026     D      ARJUN VERMA
9         PRIYA DAS   20     91  14-05-2026     A        PRIYA DAS
10       RAHUL JAIN   21     76  15-05-2026     C       RAHUL JAIN
11       NISHA IYER   19     84  15-05-2026     B       NISHA IYER
12  ADITYA KULKARNI   20     73  16-05-2026     C  ADITYA KULKARNI
13      POOJA MENON   21     97  16-05-2026     A      POOJA MENON
14    SIDDHARTH ROY   22     82  17-05-2026     B    SIDDHARTH ROY
15     KAVYA MISHRA   20     86  17-05-2026     B     KAVYA MISHRA
16      MANOJ YADAV   21     69  18-05-2026     D      MANOJ YADAV
17       ISHITA SEN   19     93  18-05-2026     A       ISHITA SEN
18      HARSHA TEJA   20     79  19-05-2026     C      HARSHA TEJA
19     NEHA CHANDRA   21     90  19-05-2026     A     NEHA CHANDRA

In [ ]:
# 6. Removing Rows
# Remove student record at index 3
df_removed_row = df.drop(index=3)

In [ ]:
# 7. GroupBy
# Average marks by department
print("Average Marks by Department:")
avg_marks = df.groupby("department")["marks"].mean()
print(avg_marks)

Average Marks by Department:
department
CIVIL    81.333333
CSE      90.400000
ECE      88.333333
EEE      79.000000
IT       85.666667
MECH     71.333333
Name: marks, dtype: float64

In [ ]:
# 8. Aggregate Functions
print("Aggregate Statistics for Marks:")

print("Mean:", df["marks"].mean())
print("Maximum:", df["marks"].max())
print("Minimum:", df["marks"].min())
print("Sum:", df["marks"].sum())
print("Median:", df["marks"].median())
print("Standard Deviation:", df["marks"].std())

Aggregate Statistics for Marks:
Mean: 83.45
Maximum: 97
Minimum: 67
Sum: 1669
Median: 84.5
Standard Deviation: 8.684377988815985

In [ ]:
# 9. Combining DataFrames
new_data = {
    "student_name": ["Teja", "Divya"],
    "age": [20, 21],
    "marks": [87, 91],
    "department": ["CSE", "ECE"]
}

new_df = pd.DataFrame(new_data)
# Match existing columns
new_df["exam_date"] = pd.NaT
new_df["grade"] = new_df["marks"].apply(assign_grade)

combined_df = pd.concat([df, new_df], ignore_index=True)

print("Combined DataFrame:")
print(combined_df)

Combined DataFrame:
       student_name  age  marks department   exam_date Grade             Name  \
0      AARAV SHARMA   20     85        CSE  10-05-2026     B     AARAV SHARMA
1        DIYA REDDY   21     92        ECE  10-05-2026     A       DIYA REDDY
2       ROHAN KUMAR   19     78       MECH  11-05-2026     C      ROHAN KUMAR
3       SNEHA PATEL   20     88        CSE  11-05-2026     B      SNEHA PATEL
4      VIKRAM SINGH   22     74        EEE  12-05-2026     C     VIKRAM SINGH
5      ANANYA GUPTA   21     95         IT  12-05-2026     A     ANANYA GUPTA
6         KIRAN RAO   20     81      CIVIL  13-05-2026     B        KIRAN RAO
7        MEERA NAIR   19     89        CSE  13-05-2026     B       MEERA NAIR
8       ARJUN VERMA   22     67       MECH  14-05-2026     D      ARJUN VERMA
9         PRIYA DAS   20     91        ECE  14-05-2026     A        PRIYA DAS
10       RAHUL JAIN   21     76         IT  15-05-2026     C       RAHUL JAIN
11       NISHA IYER   19     84        EEE  15-05-2026     B       NISHA IYER
12  ADITYA KULKARNI   20     73      CIVIL  16-05-2026     C  ADITYA KULKARNI
13      POOJA MENON   21     97        CSE  16-05-2026     A      POOJA MENON
14    SIDDHARTH ROY   22     82        ECE  17-05-2026     B    SIDDHARTH ROY
15     KAVYA MISHRA   20     86         IT  17-05-2026     B     KAVYA MISHRA
16      MANOJ YADAV   21     69       MECH  18-05-2026     D      MANOJ YADAV
17       ISHITA SEN   19     93        CSE  18-05-2026     A       ISHITA SEN
18      HARSHA TEJA   20     79        EEE  19-05-2026     C      HARSHA TEJA
19     NEHA CHANDRA   21     90      CIVIL  19-05-2026     A     NEHA CHANDRA
20             Teja   20     87        CSE         NaN   NaN              NaN
21            Divya   21     91        ECE         NaN   NaN              NaN

   grade
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20     B
21     A

In [ ]:
# 10. Working with Dates
df["Exam_date"] = pd.to_datetime(df["exam_date"])

df["day"] = df["exam_Date"].dt.day
df["month"] = df["exam_Date"].dt.month
df["year"] = df["exam_Date"].dt.year

print("extracted day, month, year:")
print(df[["exam_date", "day", "month", "year"]])

In [ ]:
# 11. Indexing
indexed_df = df.set_index("Name")

print("Details of student POOJA MENON:")
print(indexed_df.loc["POOJA MENON"])

Details of student POOJA MENON:
student_name    POOJA MENON
age                      21
marks                    97
department              CSE
exam_date        16-05-2026
Grade                     A
Name: POOJA MENON, dtype: object

In [ ]:
# 12. Pivot Table
# Average Marks for each Department
pivot = pd.pivot_table(
    df,
    values="marks",
    index="department",
    aggfunc="mean"
)

print("Pivot Table (Average Marks by Department):")
print(pivot)

Pivot Table (Average Marks by Department):
                marks
department
CIVIL       81.333333
CSE         90.400000
ECE         88.333333
EEE         79.000000
IT          85.666667
MECH        71.333333